### ISSUE TITLE
引入替换img后，提示window is not defined

### ISSUE THREAD

**Issue by divcssjs** [Caldis/react-zmage#109]
ReferenceError: window is not defined
    at ...\node_modules\react-zmage\lib\zmage.development.js:349:2
    at ...\node_modules\react-zmage\lib\zmage.development.js:338:46

当前技术栈是nextjs

**Comment by Caldis** [comment]
SSR 的话目前可以参考 [这个](https://github.com/Caldis/react-zmage/issues/5#issuecomment-506722161) 解决方案
