### ISSUE TITLE
功能不能正常使用

### ISSUE THREAD

**Issue by fanz01** [Caldis/react-zmage#11]
"react": "^16.4.0",

关闭按钮和全屏按钮都是不可用的

**Comment by fanz01** [comment]
点击关闭按钮后，webpack一直都在打包过程中

**Comment by fanz01** [comment]
根本不能正常使用呀

**Comment by Caldis** [comment]
能提供示例的相关代码或webpack配置信息吗 ?

**Comment by fanz01** [comment]
npm i react-zimage后，在程序中用Zimage标签代替img标签，然后关闭按钮和放大按钮不能正常的使用，这需要webpack的配置信息吗？
