### ISSUE TITLE
react-Zmage与ant.design Modal组件

### ISSUE THREAD

**Issue by Can-Chen** [Caldis/react-zmage#114]
在Modal组件触发后react-Zmage无法点击放大

**Comment by Caldis** [comment]
https://codesandbox.io/embed/dawn-wave-1j1dq
貌似并没有问题

**Comment by Can-Chen** [comment]
我的确在ant.Design测试，触发Modal弹框后点击图片没有触发这个组件的放大效果 
还有一个问题是，当我在把页面写到手机端页面后，图片上下排列，高度超过100%后，点击下面图片会自动弹到最上面，并且放大失败。如果文字描述不能够体现出，可以加我QQ1375883312.


------------------ 原始邮件 ------------------
发件人: "Caldis"<notifications@github.com>;
发送时间: 2019年9月9日(星期一) 晚上8:28
收件人: "Caldis/react-zmage"<react-zmage@noreply.github.com>;
抄送: "undefined"<1375883312@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Caldis/react-zmage] react-Zmage与ant.design Modal组件 (#114)




https://codesandbox.io/embed/dawn-wave-1j1dq
 貌似并没有问题

**Comment by Caldis** [comment]
@Can-Chen 我上面给出的 DEMO 在你的环境下运行有问题吗 ？
如果没有问题，请尝试更新你的 ANTD 或 Zmage 版本
如果有问题，烦请提供一下系统版本及浏览器运行环境，这样给出一个问题我也很难定位

**Comment by Can-Chen** [comment]
我刚刚仔细看了一下我的代码 问题出在我这 谢谢！！！




------------------ 原始邮件 ------------------
发件人: "Caldis"<notifications@github.com>;
发送时间: 2019年9月16日(星期一) 中午11:32
收件人: "Caldis/react-zmage"<react-zmage@noreply.github.com>;
抄送: "undefined"<1375883312@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Caldis/react-zmage] react-Zmage与ant.design Modal组件 (#114)




@Can-Chen 我上面给出的 DEMO 在你的环境下运行有问题吗 ？
 如果没有问题，请尝试更新你的 ANTD 或 Zmage 版本
 如果有问题，烦请提供一下系统版本及浏览器运行环境，这样给出一个问题我也很难定位

**Comment by Caldis** [comment]
@Can-Chen 谢谢反馈，如果是常见问题你也可以贴出来免得别人也踩坑哈

**Comment by Can-Chen** [comment]
好的



------------------ 原始邮件 ------------------
发件人: "Caldis"<notifications@github.com>; 
发送时间: 2019年9月19日(星期四) 上午10:48
收件人: "Caldis/react-zmage"<react-zmage@noreply.github.com>; 
抄送: "undefined"<1375883312@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Caldis/react-zmage] react-Zmage与ant.design Modal组件 (#114)




@Can-Chen 谢谢反馈，如果是常见问题你也可以贴出来免得别人也踩坑哈
