### ISSUE TITLE
为什么在antd pro 中关闭的时候图片卡在哪里

### ISSUE THREAD

**Issue by friendlove** [Caldis/react-zmage#12]
v

**Comment by yeyuguo** [comment]
同样的效果，主要是没有报错信息 - -

**Comment by yeyuguo** [comment]
只要点击过 control 层，那么就会缩小在中间，不位移回到图片原来的位置，不要有任何点击效果，只有 esc 键的话，就是正常的， - - 好懵逼，看代码没什么毛病

**Comment by yeyuguo** [comment]
onRest={this.handleMotionRest} 只移动到中间后，导致不会执行 该函数导致的；

**Comment by Caldis** [comment]
谢谢反馈, 我检查一下状况
能提供详细一点的复现方式吗?

**Comment by Caldis** [comment]
@friendlove @yeyuguo 
该问题已修正, 烦请测试一下, 更新至最新的 0.2.2 版本
修复位置: https://github.com/Caldis/react-zmage/commit/ccc228aed08ed3866f88da3b7f0867bb4a7a60b3#diff-a8776b0a71b57e1123977a811d35595bL1153
