### ISSUE TITLE
当传入的图片过大，放大后图片显示不全

### ISSUE THREAD

**Issue by itweblin** [Caldis/react-zmage#123]
当传入的图片过大，放大后图片显示不全（包括旋转也一样）

**Comment by Caldis** [comment]
能否提供图片尺寸范例

**Comment by itweblin** [comment]
很多，比如你手机截图这种类型，宽短，高长，比例越大越明显

**Comment by itweblin** [comment]
应该跟大小没关系，有些会，有些不会。在找问题中....（我是在antd里的table使用）

**Comment by itweblin** [comment]
transform: translate3d(-50%, -50%, 0px) translate3d(0px, 0px, 0px) scale3d(0.402427, 0.402427, 1) rotate3d(0, 0, 1, 0deg); 应该是scale3d没有计算对。不知怎么计算，不知是否有其他因素导致？

**Comment by Caldis** [comment]
我试了下貌似没有复现出来问题
https://codesandbox.io/s/autumn-https-7cp20?fontsize=14&hidenavigation=1&theme=dark

**Comment by Caldis** [comment]
不过放大后确实边缘有一点裁切，你指的是那个吗？

**Comment by itweblin** [comment]
也不是计算问题， 是裁切很多，其它项目没问题，这个项目引用就会

**Comment by itweblin** [comment]
我在看你原码在定位，现在还不知道什么因素导致

**Comment by itweblin** [comment]
问题找到了， 受全局img样式影响

**Comment by itweblin** [comment]
可以完善 Zmage中img样式宽高权重，也可以添加支持对其img样式设置

**Comment by Caldis** [comment]
全局样式覆盖修改要慎重，我也没可能每个属性都加个 important 。。。

**Comment by itweblin** [comment]
可以在 类imageLayer添加width: auto；height： auto；这样权重不高，一般的全局样式也影响不到
