### ISSUE TITLE
移动端使用没有点击放大的按钮，只有一个关闭按钮

### ISSUE THREAD

**Issue by Gxiangyu** [Caldis/react-zmage#125]
首先直接吧img改为Zmage，报错。只能使用<img src={v.value} onClick={() => Zmage.browsing({ src: v.value })} />，遇到的问题：1、关闭的按钮很大，只能手动修改大小。2、只有一个关闭按钮，其他按钮并不显示？

**Comment by Caldis** [comment]
移动端默认隐藏放大按钮, 如果需要可传入参数手动配置使其显示, 不过行为与桌面端有区别

关闭按钮过大的问题, 请问是在何种环境下产生?
