### ISSUE TITLE
引进去就报错了，根本没法使用

### ISSUE THREAD

**Issue by dongkeng001** [Caldis/react-zmage#126]
我不知道是不是react版本原因，用的是15.3.0的react版本，如果是的话，只能放弃使用了，项目比较大，不敢随意去升级react版本，怕项目后面出现奇奇怪怪问题

`Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: symbol.`

![not](https://user-images.githubusercontent.com/20589684/71387625-a9a98900-262f-11ea-8e1a-b9e0f44f0a57.png)

**Comment by Caldis** [comment]
十分抱歉, 需要 react 版本大于 v16.6.0
