### ISSUE TITLE
移动端预览图片过小

### ISSUE THREAD

**Issue by Innei** [Caldis/react-zmage#152]
![Screenshot_2020-07-22-10-30-35-944_com android chrome](https://user-images.githubusercontent.com/41265413/88127532-73081100-cc06-11ea-86b7-d9cc99a1f8ad.jpg)
![Screenshot_2020-07-22-10-30-38-452_com android chrome](https://user-images.githubusercontent.com/41265413/88127543-78655b80-cc06-11ea-8168-478ef4902989.jpg)

**Comment by Innei** [comment]
对了，最新版本的 ts 声明文件为什么删掉了呢

**Comment by takeshi-evan** [comment]
I have the same problem. Do you find a solution?

**Comment by Innei** [comment]
> I have the same problem. Did you find a solution?

换 react-medium-image-zoom 库

**Comment by takeshi-evan** [comment]
> > I have the same problem. Did you find a solution?
> 
> 换 react-medium-image-zoom 库

Thanks for the answer!
