### ISSUE TITLE
放大之后图片不会缩小，缩回原位

### ISSUE THREAD

**Issue by a728384698** [Caldis/react-zmage#18]
点击图片有放大，但是关闭之后白色背景消失，图片没有缩小还是查看模式下的图片，界面点击事件全部失效

**Comment by Caldis** [comment]
能提供一下运行的环境和相关信息吗 ?

**Comment by webPpei** [comment]
同样的问题，太卡顿了,而且收不回去
react: 16.4.1
ant-design: 3.6.5
node: 8.4.0
npm: 5.3.0

**Comment by Caldis** [comment]
@a728384698 @chengxitest @webPpei 
问题已修正, 可以更新至最新的 0.2.2 版本
修复位置: https://github.com/Caldis/react-zmage/commit/ccc228aed08ed3866f88da3b7f0867bb4a7a60b3#diff-a8776b0a71b57e1123977a811d35595bL1153
