### ISSUE TITLE
doesn't work well

### ISSUE THREAD

**Issue by LastStranger** [Caldis/react-zmage#19]
如果我把几张图片放在一起，设置了每个图片的宽度为100vw，第一张图片点击失效，点击其它图片会把几张图片加在一起以一个长图的方式出现，反而变相缩小了图片，求解？

**Comment by LastStranger** [comment]
<Zmage src={require("../assets/img/post1.png")} alt=""/>
                    <Zmage src={require("../assets/img/post2.png")} alt=""/>
                    <Zmage src={require("../assets/img/post3.png")} alt=""/>


.poster .img-container{
    font-size: 0 !important;
}

.poster>div{
    background-color: #00011d;
}

.poster div img {
    width: 100vw;
}
大概就是这样，之前代码我改了，抱歉提问题没贴代码，对了，图二和图三都是长图，会不会长图有影响？

**Comment by xuanxia** [comment]
wrapper 在有其他遮罩的时候 z-index=1000 可能会被覆盖  是否可以加参数 解决 
![image](https://user-images.githubusercontent.com/11483446/44977056-89b50880-af99-11e8-8050-f62b952fb429.png)

**Comment by Caldis** [comment]
@xuanxia 新版本增加了 zIndex 参数, 可以看一下 README.md 的说明

**Comment by xuanxia** [comment]
我在使用的时候发现只设置 z-index 无效 需要加option属性    还有我的需要中 set中的图片列表是通过异步请求获取的  是否可以将set 参数 设置成Array 和Function 2种类型  当传入方法时 取执行方法的返回值 或者回调实现。 我已经fork了 改了set 实现我的需求。 @Caldis

**Comment by Caldis** [comment]
好的, 我也在下版本增加一下这种调用方式, 也欢迎你直接提一个 PR
