### ISSUE TITLE
can not completely close when load  a  invalid picture url 

### ISSUE THREAD

**Issue by zhouzhiqiangzzq** [Caldis/react-zmage#20]
when I use zmage load a  invalid  picture url  like this 

`<Zmage
        controller={
          {
            close: true,
            zoom: false,
            flip: true,
          }
        }
        src={  invalid_url  }/>`

then I  zoom in   this picture , then close  the   **_wrapperLayer_**   still here

**Comment by Caldis** [comment]
https://github.com/Caldis/react-zmage/releases/tag/0.3.0
