### ISSUE TITLE
set无效：Invalid prop `set` supplied to `ReactZmage`.

### ISSUE THREAD

**Issue by 499800157** [Caldis/react-zmage#22]
react：^16.4.2　
react-zmage：^0.3.0
代码如下　:
import Zmage from "react-zmage";
import Img1 from "../../image/horco1.jpg";
import Img2 from "../../image/horco2.jpg";
                        
                                <Zmage src={Img1} alt="展示序列图片" set={[
                                    {
                                        src: {Img2},
                                        alt: "First image description",
                                    },{
                                        src: {Img3},
                                        alt: "Second image description",
                                    }]}
                                     />

**Comment by Caldis** [comment]
直接传入即可, 不用花括号
```
[
    {
        src: Img2,
        alt: "First image description",
    },{
        src: Img3,
        alt: "Second image description",
    }
]
```

**Comment by 499800157** [comment]
我将参数用变量定义，
const option= {
            "set":[
              {
                  src: Img2,
                  alt: "First image description",
              },{
                 src: Img3,
                alt: "Second image description",
             }
          ]
        };
在标签中使用  {...option},就可以用了，不知道在标签内为何不能直接写，不过可以用啦，感谢。

**Comment by Caldis** [comment]
会不会是你的 esLint 或者 babel 的相关配置导致 ?

因为我这边测试时完全正常
