### ISSUE TITLE
当使用set属性时，点击该图片显示的总是set设置的第一张图片

### ISSUE THREAD

**Issue by 499800157** [Caldis/react-zmage#23]
company:[
                {
                    src:companyImg1,
                    alt:"涉密计算机信息系统集成资质证书"
                },
                {
                    src:companyImg2,
                    alt:"高新技术企业批准证书"
                },
            ]
const optionCompany = {
            "set":this.state.company
        };
{this.state.company.map((item,index)=>{
                              return(
                                <div key={index}>
                                    <Zmage 
                                        src={item.src} 
                                        {...optionCompany}
                                        />
                                </div>
                              )  
                            })}

**Comment by Caldis** [comment]
就是如此, 如果需要保持同步, 将 set 的首张图片设置为 zmage 的 src 即可
这样定义的原因是用户可以直接将高分辨率的图片放到 set 的首位作为 cover 的原图以供放大查看
