### ISSUE TITLE
关闭图片时的动画 能否进行参数配置

### ISSUE THREAD

**Issue by raygongo** [Caldis/react-zmage#25]
某些使用场景下 图片高度过高 剩余部分 被隐藏的情况下  点击图片放大后
1. 点击关闭  图片缩回原位置后 有一秒的停顿 此时的图片放大的图片还未消失 但是大小会比原图 (限制了宽高) 大很多 导致遮挡住页面的其他部分 有解决办法嘛?

或者能不能 加快 关闭时的动画 这样 图片变大时 遮住其他部分的时间较短 不易发现

**Comment by Caldis** [comment]
受限于浏览器性能, 在动画执行的过程中没有对太多属性进行变换, 目前只有 position 和 scale
对于被遮挡的状况, 就更加检测不到了

之后可能会增加一个模式快速隐藏, 用来解决这种原图片进行了较多样式设定的场景

**Comment by zxj963577494** [comment]
缩略图和放大后的原图尺寸比例不同真的会卡死

**Comment by Caldis** [comment]
@zxj963577494 [0.6.11](https://github.com/Caldis/react-zmage/releases/tag/0.6.11) 之后改进了这块的处理逻辑, 如果可以, 请帮助测试一下

**Comment by zxj963577494** [comment]
@Caldis 比之前流畅了
