### ISSUE TITLE
点击图片报异常

### ISSUE THREAD

**Issue by szh0526** [Caldis/react-zmage#28]
代码
import React, { Fragment } from 'react';
import ReactDOM from 'react-dom';
import Zmage from 'react-zmage'

const mountNode = document.getElementById('root');
ReactDOM.render(<Fragment>
  <Zmage
    src="http://wdrisk.fengjr.inc/build/assets/photo.png"
    alt="最简单的使用方式"
/>
</Fragment>, mountNode);

渲染到页面上点击图片报错
VM637 vendor.dll.js:619 Uncaught Error: Expected ref to be a function or a string.

**Comment by szh0526** [comment]
。。

**Comment by Caldis** [comment]
看描述是 ref 的问题 ... 不妨检查一下代码
