### ISSUE TITLE
transform 没有兼容低版本浏览器

### ISSUE THREAD

**Issue by baxiamali** [Caldis/react-zmage#29]
transform:"translate3d(-50%, -50%, 0) translate3d("+r+"px, "+p+"px, 0px) translate3d(0px, "+l+"px, 0px) scale3d("+i+", "+i+", 1) rotate3d(0, 0, 1, "+g+"deg)"
这一段应该加上prefix~ 不然在某些浏览器上位置不正确

**Comment by Caldis** [comment]
因为这一段是 js 动态计算的, 所以没有加 Prefix
目前大部分浏览器已经对 CSS3 兼容很好了, 请问你这边出现问题的是什么版本的浏览器 ?

**Comment by baxiamali** [comment]
是低版本的safari ，IE 也会出现问题，我是修改了你的源代码实现的，只要在动态style加上下面这一段就ok了。不知道可不可以修改下~
style:{transform:"translate3d(-50%, -50%, 0) translate3d("+r+"px, "+p+"px, 0px) translate3d(0px, "+l+"px, 0px) scale3d("+i+", "+i+", 1) rotate3d(0, 0, 1, "+g+"deg)","-ms-transform":"translate3d(-50%, -50%, 0) translate3d("+r+"px, "+p+"px, 0px) translate3d(0px, "+l+"px, 0px) scale3d("+i+", "+i+", 1) rotate3d(0, 0, 1, "+g+"deg)","-moz-transform":"translate3d(-50%, -50%, 0) translate3d("+r+"px, "+p+"px, 0px) translate3d(0px, "+l+"px, 0px) scale3d("+i+", "+i+", 1) rotate3d(0, 0, 1, "+g+"deg)","-webkit-transform":"translate3d(-50%, -50%, 0) translate3d("+r+"px, "+p+"px, 0px) translate3d(0px, "+l+"px, 0px) scale3d("+i+", "+i+", 1) rotate3d(0, 0, 1, "+g+"deg)",cursor:n?"zoom-out":"initial"}


原始邮件
发件人:Caldisnotifications@github.com
收件人:Caldis/react-zmagereact-zmage@noreply.github.com
抄送:baxiamali105124767@qq.com; Authorauthor@noreply.github.com
发送时间:2018年10月9日(周二) 20:51
主题:Re: [Caldis/react-zmage] transform 没有兼容低版本浏览器 (#29)


因为这一段是 js 动态计算的, 所以没有加 Prefix
 目前大部分浏览器已经对 CSS3 兼容很好了, 请问你这边出现问题的是什么版本的浏览器 ?

**Comment by Caldis** [comment]
谢谢帮忙测试, 后续更新加上

**Comment by baxiamali** [comment]
感谢~~~~


原始邮件
发件人:Caldisnotifications@github.com
收件人:Caldis/react-zmagereact-zmage@noreply.github.com
抄送:baxiamali105124767@qq.com; Authorauthor@noreply.github.com
发送时间:2018年10月17日(周三) 10:46
主题:Re: [Caldis/react-zmage] transform 没有兼容低版本浏览器 (#29)


谢谢帮忙测试, 后续更新加上
