### ISSUE TITLE
图片无法设置触摸放大缩小

### ISSUE THREAD

**Issue by vivilauge** [Caldis/react-zmage#32]
每次用户双手触摸拉大图片之后， 整个页面的样式也变了，
希望能增加一个禁止用户双手放大图片的入口

**Comment by Caldis** [comment]
谢谢反馈, 我测试一下这个场景

**Comment by Caldis** [comment]
请设置页面的 metadata，这个应该由外部页面来保证，而不是组件本身
`<meta 
     name='viewport' 
     content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' 
/>`
