### ISSUE TITLE
放大后的图片缩放比例是否可以支持自定义。

### ISSUE THREAD

**Issue by lshyo** [Caldis/react-zmage#40]
是否能支持设置scale3d (1,1,1)。不然放大后图片会失真。

**Comment by Caldis** [comment]
这个倒是没问题, 但这样的话是否序列中的每张图片都要设置呢, 感觉会增加很多额外的配置参数

**Comment by Caldis** [comment]
Fixed at: https://github.com/Caldis/react-zmage/releases/tag/0.6.8
