### ISSUE TITLE
多图模式下，第一张图片超出展示区域

### ISSUE THREAD

**Issue by justinluo123** [Caldis/react-zmage#50]
进入查看模式显示正常
![image](https://user-images.githubusercontent.com/22760921/51101960-f7aaef80-1817-11e9-997e-8c2484ec944c.png)
当向左或者向右查看完剩余的图片再回到第一张图片的时候，会放大
![image](https://user-images.githubusercontent.com/22760921/51102015-36d94080-1818-11e9-92d6-9583742a431b.png)

**Comment by Caldis** [comment]
Fixed at: https://github.com/Caldis/react-zmage/releases/tag/0.6.8
