### ISSUE TITLE
背景设置为黑色透明时，操作图标区域背景跟随变化，图标不明显

### ISSUE THREAD

**Issue by Eaast** [Caldis/react-zmage#52]
![image](https://user-images.githubusercontent.com/12755058/51736125-4122f680-20c4-11e9-9614-224a3696c401.png)
图标区域背景默认白色会好些。

**Comment by Caldis** [comment]
是有这个问题, 后续在这块增加一个传参让用户控制图标和图标背景的颜色

**Comment by Caldis** [comment]
Add in: https://github.com/Caldis/react-zmage/releases/tag/0.7.0
直接用 ID 取对应的 SVG 图标修改 fill 属性即可, 这块不涉及到动画, 可以直接改样式
