### ISSUE TITLE
如果src的圖片為404。則取消時會有一張alt文字大圖覆蓋取消不了

### ISSUE THREAD

**Issue by HSin-Tse** [Caldis/react-zmage#55]

**Comment by Caldis** [comment]
感谢反馈

**Comment by kailong321200875** [comment]
希望图片404的时候，不要有点击放大事件

**Comment by Caldis** [comment]
Fixed in https://github.com/Caldis/react-zmage/releases/tag/0.6.11

**Comment by Caldis** [comment]
@kailong321200875 因为用户可以传入 set 来展示其他组图, 所以用封面图片是否正常加载来决定是否允许放大我感觉并不是太合适
