### ISSUE TITLE
同样一组图片，预览模式下设置的defaultPage不同，点击轮播图后效果缩放效果不一样

### ISSUE THREAD

**Issue by QianQian0826** [Caldis/react-zmage#58]
同样的一组图片，预览模式下设置不同的defaultPage，如果图片大小尺寸有区别，则进入预览模式的首页是小图片时后面图片的缩放大小基本都差不多，如果首页为较大的图片，则点击下一页再次转回来时该图片会局部放大失真

**Comment by Caldis** [comment]
Fixed in https://github.com/Caldis/react-zmage/releases/tag/0.6.11
