### ISSUE TITLE
set 的props的刚更新问题

### ISSUE THREAD

**Issue by A-birdFlyHigner** [Caldis/react-zmage#6]
index.js文件中确定是否确定不使用componentWillReceiveProps？
componentWillReceiveProps(nextProps) {
        this.setState({
            set:this.buildSet(nextProps)
        })
    }
那么如何保证当前的props是最新的，项目中已遇到该问题，自行修改了包内容，望见谅。
wapper的z-index的层级不可设置也是不好使用的一个点

**Comment by Caldis** [comment]
@A-birdFlyHigner 感谢反馈

之前没有考虑过动态更新当前图片的场景，后续更新会修复
关于设置 wrapper 的 z-index，想了解一下大致是自什么场景下使用？

**Comment by A-birdFlyHigner** [comment]
我页面上有层级较高的组建的时候，会浮于展开图片上方的
