### ISSUE TITLE
放大时动画不一致

### ISSUE THREAD

**Issue by HeJueting** [Caldis/react-zmage#63]
请问，当我设置成可展示序列图片时，第一张图的动画为什么会跟其他图片动画不一致？其他图片动画都是从上滑下来至全屏，而第一张图片动画是点击处放大至全屏。详情点击下图查看（gif图片加载可能有点慢.....）

http://www.shmily-hjt.cn/problem.gif

**Comment by Caldis** [comment]
目前判断逻辑是只要 defaultPage 不为 0, 就会从上方弹出
这块确实有优化空间, 应该是 defaultPage 对应的 src 跟封面展示的 src 相同就应该从点击处弹出才对

我在后续的版本优化一下这个, 谢谢你的反馈

**Comment by Caldis** [comment]
https://github.com/Caldis/react-zmage/releases/tag/0.8.1
