### ISSUE TITLE
动画报错Unsupported vendor-prefixed style property mozTransform. Did you mean MozTransform?

### ISSUE THREAD

**Issue by zwhello** [Caldis/react-zmage#69]
Unsupported vendor-prefixed style property mozTransform. Did you mean MozTransform?
Unsupported vendor-prefixed style property webkitTransform. Did you mean WebkitTransform?
Unsupported vendor-prefixed style property oTransform. Did you mean OTransform?

**Comment by Caldis** [comment]
感谢反馈, 我本地编译倒是没有出现这个提示, 先修了

**Comment by zenghr0820** [comment]
怎么决解动画报错？

**Comment by Tooccooo** [comment]
> 感谢反馈, 我本地编译倒是没有出现这个提示, 先修了

这个bug更新了吗

**Comment by yuanguandong** [comment]
希望提供受控属性
this.zmage.setState({
      browsing:true
    })
这样的确报一个警告

**Comment by Caldis** [comment]
Fixed in [0.7.5](https://github.com/Caldis/react-zmage/releases/tag/0.7.5)
