### ISSUE TITLE
动画报错Unsupported vendor-prefixed style property webkitTransform. Did you mean WebkitTransform?

### ISSUE THREAD

**Issue by purelugs** [Caldis/react-zmage#70]
Unsupported vendor-prefixed style property webkitTransform. Did you mean WebkitTransform?

**Comment by yuanguandong** [comment]
the same to me

**Comment by Caldis** [comment]
Fixed in [0.7.5](https://github.com/Caldis/react-zmage/releases/tag/0.7.5)
