### ISSUE TITLE
typescript下如何使用

### ISSUE THREAD

**Issue by 997282173** [Caldis/react-zmage#74]
typescript下如何使用, 没有@types/react-zmage库

**Comment by qianbaiduhai** [comment]
自己声名一个*.d.ts文件，之后引用，最简单的，在global中
```tsx
declare module 'rc-calendar/lib/FullCalendar' {
    const obj: any
    export = obj
}
```

**Comment by ddzy** [comment]
> typescript下如何使用, 没有@types/react-zmage库

已pr: https://github.com/Caldis/react-zmage/pull/111
