### ISSUE TITLE
请问如果是html字符串中img标签该如何使用？

### ISSUE THREAD

**Issue by plainnany** [Caldis/react-zmage#76]
你好，我这里目前数据格式是`'<div><img src= /></div>'`这样的字符串，所以直接使用的是react 的dangerouslySetInnerHTML，我尝试把img字符 替换为 Zmage，但是没什么用，如果想用Zmage的话，这种应该怎么处理呢？

**Comment by Minoyu** [comment]
同样想问这样的问题

**Comment by Caldis** [comment]
纯文本确实没有什么好办法, 任何组件都是这样, 不过新版本支持函数调用, 你可以尝试将 Zmage 的引用挂载到 windows 对象, 然后使用内联的 js 方法来调用并弹出
