### ISSUE TITLE
放大的图片有点问题

### ISSUE THREAD

**Issue by MaZhengA** [Caldis/react-zmage#77]
![image](https://user-images.githubusercontent.com/33256699/57500408-e5e4df00-7315-11e9-95d6-3852e2a11a31.png)
就比如这样，我点击了第二张，结果放大的是第一张！
我想请问一下这是怎么回事？是我的用法存在问题么？
我看你的文档里边写了一句：
// 如果设置了 Set, 则进入查看模式后第一张图片将会是 set 的首图, 而不是 src
// 如果你需要在查看模式中呈现高精度图片, 可以将其设置为 set 的首图, 或使用 defaultPage 指定
我想是不是这个原因？因为我设置了set，所以不管我点哪一张，最后出来的都是第一张

**Comment by Caldis** [comment]
```
const imgSet= [{ src:img1 }, { src:img2 }, { src:img3 }]
<Zmage src={img1} set={imgSet} defaultPage={0}/>
<Zmage src={img2} set={imgSet} defaultPage={1}/>
<Zmage src={img3} set={imgSet} defaultPage={2}/>
```
依顺序将每张图片的 ```defaultPage``` 参数设置为其 set 中图片中其对应的下标即可

**Comment by MaZhengA** [comment]
好了，谢谢了
