### ISSUE TITLE
first one is working sometime but from second its not working

### ISSUE THREAD

**Issue by himadrinath** [Caldis/react-zmage#79]
@Caldis  in my list their are many carousals first carousal working sometime but from second it not working i am using it under react-lazyload

take a look at this

![zmage](https://user-images.githubusercontent.com/12247490/57965363-f540d980-7960-11e9-8eee-6e6fb2021fe3.gif)

**Comment by himadrinath** [comment]
@Caldis if i scroll the page its not working and if i don't its working

**Comment by himadrinath** [comment]
It's fixed. Because of the body height the problem happening.

**Comment by Caldis** [comment]
@himadrinath Thanks for the feedback
