### ISSUE TITLE
图片旋转

### ISSUE THREAD

**Issue by JDemonde** [Caldis/react-zmage#8]
你好 我想问下 由于后台传过来的图片全都是倒立的 排列的时候可进行旋转 但是放大后不能旋转（还是倒立的） 请问怎么更改放大后的旋转呢（如果进行更改.imageLayer__1CUl类名进行旋转的话  动画就没有了 很是突兀）

**Comment by Caldis** [comment]
暂时不支持这样的功能，因为同时处理太多动画属性的话会导致掉帧很明显，十分抱歉
