### ISSUE TITLE
图片svg全屏效果问题

### ISSUE THREAD

**Issue by pennchester** [Caldis/react-zmage#81]
当预览的是svg图片时，图片超出了屏幕，无法查看完整，也不能进行移动查看

**Comment by Caldis** [comment]
不建议直接预览 SVG 文件, 因为 SVG 文件有内置的 width/height 和 viewport/viewbox 等影响缩放的参数, 可以尝试用 img 标签来渲染 svg, 这样宽高是可控的

**Comment by pennchester** [comment]
那是否可以在内部增加处理，或者提供出重新渲染页面的接口
