### ISSUE TITLE
点击翻页会报错

### ISSUE THREAD

**Issue by destinyGKH** [Caldis/react-zmage#92]
点击翻页会报错，原因是state没有初始化，所以拿不到set。其他地方用props就没问题。
![Selection_999(093)](https://user-images.githubusercontent.com/11714252/61030605-52e92380-a3f0-11e9-9396-871f3af43b8d.png)

**Comment by Caldis** [comment]
是已经更新到最新版本了吗 ？

**Comment by destinyGKH** [comment]
是的，用的最新版的0.8.1。

**Comment by Caldis** [comment]
能否提供调用的代码，我这边暂时无法复现

**Comment by Caldis** [comment]
@destinyGKH 这个是 0.8.1 的问题，已经修复了，更新到 0.8.3 即可
