### ISSUE TITLE
怎么实现图片预览，控制预览的高度和宽度

### ISSUE THREAD

**Issue by mengGit66** [Caldis/react-zmage#95]
您好，怎么实现预览图片后，可以控制预览图的高度和宽度，包括按钮的位置，

**Comment by Caldis** [comment]
目前只能通过 ```edge``` 参数来控制距离屏幕的边距，位置不可以调整
按钮位置你可以通过绑定特定的选择器来覆盖样式，都有对应的 ID 可以直接选择
