### ISSUE TITLE
switch image时候有参数控制动画效果么？

### ISSUE THREAD

**Issue by shijuanjuan93** [Caldis/react-zmage#97]
switch image 时候有参数控制简单切换页面么，因为系统原因，可能不想要动画那种深浅切换效果。 看了文档没有相关说明，谢谢啦

**Comment by Caldis** [comment]
你可以传入 ```animate``` 参数来控制切换样式，[参考](https://github.com/Caldis/react-zmage/blob/9e13e09fe77b7944251af8b8d1b453c21d7e0445/src/config/default.js#L88)
如果不能用请更新一下版本
